version: 0.2
env:
  variables:
    APP_NAME: "todo-angular-app"
phases:
  install:
    runtime-versions:
      nodejs: 12.20
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - npm run build
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - ls -la
      - cd dist/$APP_NAME
      - aws s3 sync . s3://pranesh-todoapp --delete
