version: 0.2
env:
  variables:
    APP_NAME: "todo-list"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - npm run build
  post_build:
    commands:
      - mv appspec.yml ./dist/$APP_NAME
      - mv scripts ./dist/$APP_NAME
#   post_build:
#     commands:
#       - echo build process finished, we should uplload to S3 now
#       - cd dist/$APP_NAME
#       - ls -la
#       - aws s3 sync . s3://pranesh-todoapp --delete
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/$APP_NAME
